* Install Unifi Controller
** Network map

#+BEGIN_SRC
internet <--->   UniFi USG <-- LAN 1 --> UniFi Controller
                      ^
                      | LAN 2
                      v
participants <---> unmanaged switch <---> wireless AP
#+END_SRC

Most of the configuration takes place on the Unifi controller.

We run the controller ourselves on Debian, with the Unifi controller software installed.
** TODO Willem: Add description of how to install unifi controller on Debian
** Mating UniFi Controller and USG
   The UniFi controller and USG may not mate (connect) automatically. For this
   to work, SSH into the USG (default username and password is ~ubnt:ubnt~), and
   execute the following:

#+BEGIN_SRC ssh
mca-cli
set-inform http://ip-of-controller:8080/inform
# go to the controller web interface, login, go to the devices tab, approve the connection, and again:
set-inform http://ip-of-controller:8080/inform
#+END_SRC

** Theory of operation

*** Participant flow

   1. Participant arrives at LAN, connects PC to network
   2. Participant goes to a webpage
   3. Participant is redirected to http://portal.gepwnage.lan
   4. Participant enters his voucher and clicks "Register on network"
   5. Participant is redirected to the status page
   6. Participant has access to the network
   
*** Portal <-> Unifi Controller communication

   1. When the participant visits http://portal.gepwnage.lan, the portal takes
      the IP of the user, and requests all the leases from the unifi controller.
      From here, the portal finds the MAC address of the user, which the
      controller needs to approve the lease.
   2. When the voucher is entered into the portal, the portal verifies the voucher.
      And if it is valid, the lease is approved.
   
   The relevant API calls are:

   - ~list_clients()~, to retreive all clients so we can get the MAC address from the local IP.
     - [[https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L984][API Call]]
   - ~authorize_guest()~, to authorize the participant on the LAN network.
     - [[https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L206][API Call]]
   
   Note: for API communication we use [[https://github.com/Art-of-WiFi/UniFi-API-client][art-of-wifi/unify-api-client]]. And an example for how a portal
   can work, can be found at [[https://github.com/kaptk2/portal][kaptk2/portal]].

** Network configuration
   As seen in the Network Map, the UniFi USG has two ports. We use LAN1 for the 'Corporate' network,
   without captive portal. And we use LAN2 for the 'Guest' network.

   Everyone, except for the controller and select circumstances, is in the LAN2 'Guest' network. Which,
   by default, blocks all network access except for allowed users.

** Configuring static DNS routes

   Edit ~/usr/lib/unifi/data/sites/default/config.gateway.json~ and configure as follows for static DNS:

#+BEGIN_SRC json
{
    "system": {
        "static-host-mapping": {
            "host-name": {
                "portal.gepwnage.lan": {
                    "inet": [
                        "10.13.42.3"
                    ]
                }
            }
        }
    }
}
#+END_SRC
   
* Sources
  - https://help.ubnt.com/hc/en-us/articles/220066768-UniFi-How-to-Install-Update-via-APT-on-Debian-or-Ubuntu
  - http://jzdocs.com/ways-to-install-a-ubiquiti-unifi-security-gateway-usg/
